# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: ryanlewis.ccsesh
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: ccsesh.exe
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ryanlewis/ccsesh/releases/download/v0.1.0/ccsesh-x86_64-pc-windows-msvc.zip
    InstallerSha256: PLACEHOLDER_SHA256_WINDOWS_X64
ManifestType: installer
ManifestVersion: 1.9.0
